# Generated by Django 3.1 on 2021-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
