# Generated by Django 3.1 on 2021-07-01 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apikey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=60)),
                ('app_key', models.CharField(max_length=255)),
                ('market_key', models.CharField(max_length=255)),
                ('app_sacret', models.CharField(max_length=255)),
                ('market_sacret', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('Copy_percent', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
